name: marketplace_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0  # Current dart Version Dart 3.8.0 (used by Flutter 3.32.0)

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_dotenv: ^5.1.0
  flutter_vector_icons: ^2.0.0
  cross_connectivity: ^3.2.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  provider: ^6.1.2
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_hooks: ^0.20.5
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.2.3
  get_storage: ^2.1.1
  page_view_dot_indicator: ^2.3.0
  flutter_otp_text_field: ^1.1.3+2
  webview_flutter_android: ^3.16.3
  webview_flutter: ^4.8.0
  webview_flutter_wkwebview: ^3.13.1
  # webview_universal: ^0.0.5
  # google_maps_flutter: ^2.6.1
  get_time_ago: ^2.3.0
  google_sign_in: ^6.3.0
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  path: ^1.9.0
  web_socket_channel: ^2.1.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  url_launcher: ^6.2.5
  # Firebase dependencies
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^17.2.3
  uuid: ^4.3.3
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#8B6F47"
    theme_color: "#8B6F47"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/